"""
Eyxa backend - FastAPI application entry point.

Starts uvicorn with TLS when run directly:
    python main.py

Or externally:
    uvicorn main:app --ssl-keyfile certs/key.pem --ssl-certfile certs/cert.pem
                     --host 0.0.0.0 --port 8443

Development TLS:
    Self-signed cert in certs/ (generated by gen_cert.bat).
    Agent uses HKLM\\SOFTWARE\\Eyxa\\SkipTlsVerify=1 to bypass validation.

HARDENING: Remove SkipTlsVerify and replace cert before Phase 9 validation.

Dashboard:
    The built React SPA is served from backend/static/ at route /*.
    Build with: cd dashboard && npm run build (output goes to backend/static).
    Run dev frontend separately with: npm run dev (proxied to :8443).
"""

import pathlib
import uvicorn
from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from contextlib import asynccontextmanager
from db.database import init_db
from api.enroll    import router as enroll_router
from api.ingest    import router as ingest_router
from api.responder import router as responder_router
from api.auth      import router as auth_router
from api.dashboard import router as dashboard_router
from api.alerts_api import router as alerts_router
from api.ai_api import router as ai_router
from api.rules_api  import router as rules_router
from api.hunt       import router as hunt_router
from api.admin_api  import router as admin_router
from api.export     import router as export_router
from detection.engine import engine_loop


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Initialise DB schema on startup; start detection engine background loop."""
    import asyncio
    # Suppress Windows asyncio proactor connection_lost ConnectionResetError spam
    loop = asyncio.get_running_loop()
    def _silence_proactor(l, ctx):
        msg = ctx.get("message", "")
        exc = ctx.get("exception")
        if "connection_lost" in msg or (exc and "10054" in str(exc)):
            return
        l.default_exception_handler(ctx)
    loop.set_exception_handler(_silence_proactor)

    init_db()
    
    # Force sync rules from disk every time the backend boots
    from db.database import get_connection
    from api.rules_api import seed_rules_from_disk
    conn = get_connection()
    seed_rules_from_disk(conn)
    conn.close()
    task = asyncio.create_task(engine_loop())
    try:
        yield
    finally:
        task.cancel()


app = FastAPI(
    title="Eyxa Backend",
    version="0.2.0",
    lifespan=lifespan,
    docs_url=None,
    redoc_url=None,
)

# CORS - allow any origin during development/demo while supporting cookies
app.add_middleware(
    CORSMiddleware,
    allow_origin_regex=".*",
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- Agent routes (existing, unchanged) ---
app.include_router(enroll_router)
app.include_router(ingest_router)
app.include_router(responder_router)

# --- Dashboard API routes (new) ---
app.include_router(auth_router, prefix="/api")
app.include_router(dashboard_router, prefix="/api")
app.include_router(alerts_router, prefix="/api", tags=["alerts"])
app.include_router(ai_router, prefix="/api", tags=["ai"])
app.include_router(rules_router, prefix="/api")
app.include_router(hunt_router, prefix="/api")
app.include_router(admin_router, prefix="/api")
app.include_router(export_router, prefix="/api")


# --- Serve React SPA from static/ ---
_STATIC = pathlib.Path(__file__).parent / "static"
_STATIC.mkdir(exist_ok=True)
_ASSETS = _STATIC / "assets"
if _ASSETS.exists():
    app.mount("/assets", StaticFiles(directory=str(_ASSETS)), name="assets")


@app.get("/")
def serve_root(request: Request):
    index = _STATIC / "index.html"
    if index.exists():
        return FileResponse(str(index))
    return {"error": "Dashboard static files missing. Run 'npm run build' inside dashboard/"}


@app.get("/{full_path:path}")
def spa_fallback(request: Request, full_path: str):
    if full_path and not full_path.startswith("api/"):
        requested_file = _STATIC / full_path
        if requested_file.is_file():
            return FileResponse(str(requested_file))

    index = _STATIC / "index.html"
    if index.exists():
        return FileResponse(str(index))
    return {"error": "Dashboard static files missing. Run 'npm run build' inside dashboard/"}


if __name__ == "__main__":
    import pathlib
    certs = pathlib.Path(__file__).parent / "certs"
    uvicorn.run(
        "main:app",
        host="0.0.0.0",
        port=8443,
        ssl_keyfile=str(certs / "key.pem"),
        ssl_certfile=str(certs / "cert.pem"),
        log_level="info",
    )
